kafka:
    bootstrap-servers: "localhost:9092"
    topic: "test"
    group-id: "test-group1"
    client-id: "test-client1"
    CONSUMER_FETCH_MIN_BYTES: 1
    CONSUMER_FETCH_MAX_BYTES: 10485760
    CONSUMER_RETRIES: 3
    CONSUMER_RETRY_BACKOFF_MS: 100
    CONSUMER_MAX_BATCH_SIZE: 16384
    CONSUMER_MAX_BATCH_DELAY_MS: 100
    CONSUMER_OFFSET_COMMIT_INTERVAL_MS: 5000
    CONSUMER_AUTO_OFFSET_RESET: "latest"
    CONSUMER_MIN_IN_FLIGHT_BYTES: 1
    CONSUMER_MAX_IN_FLIGHT_BYTES: 10485760
postgres:
    connection-string: "User ID=logger;Password=logger;Host=localhost;Port=5432;Database=logger;Pooling=false;"